- platform: command_line
  switches:
    lounge_tv_power:
      friendly_name: tv
      command_on: 'curl -X POST http://192.168.1.33:8060/keypress/PowerOn'
      command_off: 'curl -X POST http://192.168.1.33:8060/keypress/PowerOff'
      command_state: 'curl -s GET http://192.168.1.33:8060/query/device-info | grep power-mode | sed -e "s:<power-mode>DisplayOff</power-mode>:OFF:" -e "s:<power-mode>PowerOn</power-mode>:ON:"'
      value_template: '{{ value == "ON" }}'